local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>ct", builtin.colorscheme, {})
vim.keymap.set("n", "<leader>ts", builtin.planets, {})
vim.keymap.set("n", "<leader>fs", builtin.live_grep, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})

vim.keymap.set("n", "<leader>fo", builtin.lsp_document_symbols, {})
vim.keymap.set("n", "<leader>fg", builtin.git_status, {})
vim.keymap.set("n", "<leader>fc", builtin.treesitter, {})
